[package]
name = "window-manager"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.9.0"
log = {version="0.4.14", features=["release_max_level_warn"]}
simple_logger = "1.13.0"
